name: build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    name: gpu
    steps:
      - uses: actions/checkout@v2
      - name: Activating conda env
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh 
          conda activate fastgraphml
      - name: Run pytest in conda env
        run: conda run -n fastgraphml pytest 
