name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.13"
          cache: pip
          cache-dependency-path: setup.py
      - name: Setup pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install packages
        run: pip install black==22.8.0 mypy==0.981 flake8==5.0.4 isort==5.10.1
      - name: Run black
        run: black --check --verbose --diff --color ./
      - name: Run isort
        run: isort --check .
      - name: Run mypy
        run: mypy ./graph_embeddings
      - name: Run flake8
        run: flake8 ./graph_embeddings
